### ISSUE TITLE
CephFS: cephadm bootstrap fails with `EINVAL`

### ISSUE THREAD

**Issue by anoopcs9** [samba-in-kubernetes/sit-test-cases#94]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/tmp2_xhpnf4.cephadm.build/app/__main__.py", line 5644, in <module>
  File "/tmp/tmp2_xhpnf4.cephadm.build/app/__main__.py", line 5632, in main
  File "/tmp/tmp2_xhpnf4.cephadm.build/app/__main__.py", line 2673, in _rollback
  File "/tmp/tmp2_xhpnf4.cephadm.build/app/__main__.py", line 453, in _default_image
  File "/tmp/tmp2_xhpnf4.cephadm.build/app/__main__.py", line 2939, in command_bootstrap
  File "/tmp/tmp2_xhpnf4.cephadm.build/app/__main__.py", line 2437, in prepare_dashboard
  File "/tmp/tmp2_xhpnf4.cephadm.build/app/__main__.py", line 2852, in cli
  File "/tmp/tmp2_xhpnf4.cephadm.build/app/cephadmlib/container_types.py", line 430, in run
  File "/tmp/tmp2_xhpnf4.cephadm.build/app/cephadmlib/call_wrappers.py", line 307, in call_throws
RuntimeError: Failed command: /bin/podman run --rm --ipc=host --stop-signal=SIGTERM --net=host --entrypoint /usr/bin/ceph --init -e CONTAINER_IMAGE=quay.ceph.io/ceph-ci/ceph:main-ad7c409-centos-stream9-x86_64-devel -e NODE_NAME=storage0 -v /var/log/ceph/77bca49a-9b55-11ef-ae26-5254004c7af8:/var/log/ceph:z -v /tmp/ceph-tmpxdrmjp6r:/etc/ceph/ceph.client.admin.keyring:z -v /tmp/ceph-tmpvssnezvo:/etc/ceph/ceph.conf:z quay.ceph.io/ceph-ci/ceph:main-ad7c409-centos-stream9-x86_64-devel config set mgr mgr/dashboard/ssl_server_port 8443: Error EINVAL: unrecognized config option 'mgr/dashboard/ssl_server_port'
```

**Comment by anoopcs9** [comment]
Based on the timeline I narrowed it down to the following range of commits:
```
$ git log de3c6e4..ad7c409 --oneline 
ad7c409fc28 Merge pull request #60549 from phlogistonjohn/jjm-smb-dataclass-config
2cbef7195a4 Merge pull request #60451 from rhcs-dashboard/nvmeof-conf-rm-fix
72e7e1078bd Merge pull request #60377 from adk3798/cephadm-share-default-images
944d4125169 Merge pull request #60281 from phlogistonjohn/jjm-change-cluster-validate
9190d057fc8 Merge pull request #60096 from adk3798/maintenance-mode-dead-host
43658087d49 Merge pull request #59957 from adk3798/cephadm-bootstrap-global-public-network
c6ee0812028 Merge pull request #59838 from cbodley/wip-68083
0bddaf4ce6c Merge pull request #59644 from wlritchi/boost-1.86-compat
11454f9f543 Merge pull request #59568 from badone/wip-tracker-65235-noscrub-to-ignorelist
873057e3f38 Merge pull request #60453 from cbodley/wip-librados-dup
408c10613e8 Merge pull request #54954 from diffs/main
81e274bd059 Merge pull request #55693 from adk3798/cephadm-nfsv3
874f12451da cephadm: update default image imports to point to common location
297f9f94b3c cephadm: add python-common/ceph to MYPYPATH and pytest PYTHONPATH
b1b9cc0c84f python-common: add spot in python-common for cephadm default images
b44121f4832 cephadm: add python-common/ceph to cephadm zipapp
2b30c8e8958 cephadm/smb: convert config object to use a dataclass
b23b0407fec librados: dont duplicate class names in member definitions
4080115739d mgr/dashboard: rm nvmeof conf based on its daemon name
18b8277e86e mgr/cephadm: add "Enable_UDP = false;" to ganesha conf
4d795a8ea41 mgr/cephadm: add "mount_path_pseudo = true;" to generated ganesha conf
1e69ebc6cea mgr/cephadm: add NFSv3 protocol to cephadm generated ganesha conf
b39be5abe03 mgr/nfs: add NFSv3 protocol to exports
565bb1407a9 doc/cephadm: document new flags on maintenance exit command
ee9b7c0617c mgr/cephadm: add offline host handling to maintenance exit
eaad13485b8 mgr/cephadm: set maintenance mode healthcheck when removing hosts
da89acdc850 mgr/smb: prevent switching between clustering modes
263c0f8e730 mgr/smb: move logic validating cluster changes to handler
2f7fe668fe2 mgr/smb: split _check_cluster function body into two functions
3ec02970325 cephadm: make bootstrap default to "global" section for public_network setting
9d454bd8be6 os: remove unused btrfs_ioctl.h and tests
a98c0d67b63 common: remove unused sync_filesystem.h
01306208eac src/include/uuid.h: fix for boost 1.86.0
f011cc22627 qa: Add ignorelist entries for reef-x tests
b01453b1c1b osd: remove unnecessary return statements
78d6bfe54c3 osd: add clear_shards_repaired command
```

Last known good commit: de3c6e4

**Comment by anoopcs9** [comment]
Bootstrap command used:
`/root/cephadm bootstrap --mon-ip 192.168.122.100 --ssh-private-key /root/.ssh/id_rsa --ssh-public-key /root/.ssh/id_rsa.pub --skip-monitoring-stack`

**Comment by spuiuk** [comment]
Just expanding the errors seen in the original summary.

```
RuntimeError: Failed command: /bin/podman run --rm --ipc=host --stop-signal=SIGTERM --net=host --entrypoint /usr/bin/ceph --init -e CONTAINER_IMAGE=quay.ceph.io/ceph-ci/ceph:main-ad7c409-centos-stream9-x86_64-devel -e NODE_NAME=storage0 -v /var/log/ceph/77bca49a-9b55-11ef-ae26-5254004c7af8:/var/log/ceph:z -v /tmp/ceph-tmpxdrmjp6r:/etc/ceph/ceph.client.admin.keyring:z -v /tmp/ceph-tmpvssnezvo:/etc/ceph/ceph.conf:z quay.ceph.io/ceph-ci/ceph:main-ad7c409-centos-stream9-x86_64-devel
config set mgr mgr/dashboard/ssl_server_port 8443:
Error EINVAL: unrecognized config option 'mgr/dashboard/ssl_server_port'
```

**Comment by anoopcs9** [comment]
upstream issue tracker: https://tracker.ceph.com/issues/68834

**Comment by anoopcs9** [comment]
Fixed with https://github.com/ceph/ceph/pull/60602.
